language: ruby
dist: trusty

rvm:
  - 2.5.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

services:
  - postgresql

addons:
  postgresql: 9.6

install:
  - bundle install
  - yarn install
  - bundle exec rubocop
