language: ruby
dist: trusty

rvm:
  - 2.5.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

services:
  - postgresql

addons:
  postgresql: 9.6

install:
  - nvm install v8.11.4
  - bundle install
  - nvm use v8.11.4
  - yarn --cwd client install

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database planning_poker;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rspec
  - yarn --cwd client lint
  - yarn --cwd client build
  - yarn --cwd client unit
