language: ruby
dist: trusty

rvm:
  - 2.5.0

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

services:
  - postgresql

addons:
  postgresql: 9.6

install:
  - nvm install v8.11.4
  - bundle install
  - yarn install

before_script:
  - nvm use v8.11.4

script:
  - bundle exec rubocop
  - bundle exec rspec
  - yarn run lint
  - yarn run test
